apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: priponka-podpore-referendum-dostojna-smrt-2025
    newName: rg.fr-par.scw.cloud/djnd/priponka-podpore-referendum-dostojna-smrt-2025
    newTag: '3aa8ead4a3e7dd59060905ff9985a86a249cb998'
