apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: priponka-podpore-referendum-dostojna-smrt-2025
    newName: rg.fr-par.scw.cloud/djnd/priponka-podpore-referendum-dostojna-smrt-2025
    newTag: '2000605de9a002ac30a3615367a56c185077d8b6'
