apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: priponka-podpore-referendum-dostojna-smrt-2025
    newName: rg.fr-par.scw.cloud/djnd/priponka-podpore-referendum-dostojna-smrt-2025
    newTag: '7d602be33fda50201ebd32f74a949ba2c5c4d8e6'
