apiVersion: v1
kind: Service
metadata:
  name: priponka-podpore-referendum-dostojna-smrt-2025
spec:
  selector:
    app: priponka-podpore-referendum-dostojna-smrt-2025
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
